### ISSUE TITLE
Carpentries glosario

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/glossary#1]
Should we also use https://github.com/carpentries/glosario?

@yabellini @paocorrales @eliocamp

**Comment by maelle** [comment]
it has actual definitions not translations, though

**Comment by maelle** [comment]
although one can find translations via the cross links

**Comment by yabellini** [comment]
Yes. I have that one mention on the guidelines. We can use to check some words.

**Comment by maelle** [comment]
Oops it did sound familiar, sorry :woman_facepalming: In any case if you want me to write some code to get a csv out of it please ping me!
